version: "3.7"

services:
  pgsql:
    image: postgres:13.1-alpine
    container_name: pgsql-dev
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: "Europe/Amsterdam"
      PGTZ: "Europe/Amsterdam"
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: